### ISSUE TITLE
place_order() return False with using the simulated account

### ISSUE THREAD

**Issue by mymusise** [tigerfintech/openapi-python-sdk#11]
It looks like the `response_content` is different when using the simulated account.
The `place_order()` function return `False` but the order is created successfully.

https://github.com/tigerfintech/openapi-python-sdk/blob/61cf7cad54db7243b59b920583dbec2516ff3f53/tigeropen/trade/trade_client.py#L213

**Comment by amoygao** [comment]
fixed is new version 1.1.0
