### ISSUE TITLE
The repo is TOOOO large

### ISSUE THREAD

**Issue by bg5hfc** [tigerfintech/openapi-python-sdk#2]
There are only a couple of python files in this repo, but its size is above 40M+, that's too bad. 
It really needs a rebase and a forced-push before it's too late.

**Comment by bg5hfc** [comment]
Maybe you would like to **use this command to rebase repo from commit 097c27..**

> git rebase -i -q --committer-date-is-author-date 097c27

and modify commit log like this, then :wq to continue:

```
pick fa0f60d ADD:python openapi sdk
squash 3bc25af MOD:rm dependency
pick 3697f3d MOD:requirements
pick 02b169c MOD:fix
squash 519a109 MOD:fix
squash c75eec7 MOD:fix
squash 3344a9b MOD:-cache
squash 1b28f93 -cache
pick 2e97e03 Create README.md
pick c6c3245 fix: encode issue
pick 8c31d81 add docs

# Rebase 097c277..8c31d81 onto 097c277 (11 commands)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```
and you need typing another :wq twice to confirm squashed log messages, 

now you can see the simplified commits , meanwhile the size of the repo is reduced to about 50KiB.

**use --force to override the remote commits.**

> git push --force origin master

At last,  remember adding the .gitignore file.

**Comment by amoygao** [comment]
fixed, thanks.
