### ISSUE TITLE
你们的实盘跟模拟没有隔离的吗？

### ISSUE THREAD

**Issue by viponedream** [tigerfintech/openapi-python-sdk#26]
我在后台有这么几个号码  https://www.tigersecurities.com/openapi/info
账户ID	Uxxxxx
模拟账户	20190309180434367  用于模拟交易，支持美港股
tiger_id	2015xxxx
------------------------------------------------------------
如果我要模拟的话
TigerOpenClientConfig要提供哪些号码呢？
我的 account 使用模拟号码， 登录之后，它把实盘号码的持仓以及实盘的余额都推送回来。
也就是模拟持仓100万以及实盘的全部都推送来了。
这样我都不敢操作了。

你们的实盘跟模拟没有隔离的吗？

------------------------------------------------------------
如果我要实盘交易以及模拟交易应该分别怎样操作呢？

**Comment by zzzyb** [comment]
tigerid 用于获取信息，在推送的接口里面，会推送同一个 tigerid 下的所有账户的信息。
实际交易（订单操作，查询持仓）等是和账户相关的。 调用这些API的使用 需要传入account，指定下单的账户（标准、环球、模拟）。
