### ISSUE TITLE
Help to update IP whilelist on the Quantitative Platform

### ISSUE THREAD

**Issue by tmonip** [tigerfintech/openapi-python-sdk#38]
Hi, This is probably not relevant to the bug or feature of this repository but I don't know where to ask for help.
I am not able to reset/update the IP whilelist on the https://quant.tigerfintech.com/#developer platform.
I am able to update the public key only. I've lost the access to the previous IP address since it wasn't fixed.
I'd appreciate if you can help or point me to a direction where I can seek for a support on the platform.
Thanks!

**Comment by lijiawen** [comment]
Does the problem still exist?

**Comment by tmonip** [comment]
@lijiawen it has been resolved. Thanks! Issue closed.
