### ISSUE TITLE
Error while run  python setup.py

### ISSUE THREAD

**Issue by suetli** [tigerfintech/openapi-python-sdk#68]
Hi, Encountered this error while run the python setup.py, please help, 
how could i solve this. 

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by hotea** [comment]
you can run python setup.py sdist and generate a package, such as `tigeropen-3.0.3.tar.gz` then install the package by `pip install tigeropen-3.0.3.tar.gz`
