### ISSUE TITLE
[{'name': 'aStockQuoteLv1', 'expire_at': -1}]

### ISSUE THREAD

**Issue by suetli** [tigerfintech/openapi-python-sdk#69]
i got this Quote after i run the quoteclient.py.

may i know what does it means for aStockQuoteLv1。
i could not find this in the list .

**Comment by hotea** [comment]
It means china mainland stock quote permission.

https://quant.itigerup.com/openapi/en/python/permission/feePermission.html#how-to-subscribe-to-api-market-data
